# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Polyponic
email: support@polyponic.com
description: Find inspiration for aquaponic systems, hydroponic systems, vermiponic systems or mix it up for a unique polyponic system. From systems that fit in a cup to systems to fill up a warehouse, you can learn a little something here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://polyponic.com" # the base hostname & protocol for your site
twitter_username: US_polyponic
github_username:  polyponic

# Build settings
markdown: kramdown
collections:
  output: true
